name:                hello-lenses
version:             0.1.0.0
homepage:            "https://gitlab.com/neosimsim/hello-lenses"
git:                 "https://gitlab.com/neosimsim/hello-lenses.git"
bug-reports:         "https://gitlab.com/neosimsim/hello-lenses/issues"
license:             BSD3
author:              "Alexander Ben Nasrallah"
maintainer:          "me@abn.sh"
copyright:           "2019 © Alexander Ben Nasrallah"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitLab at <https://gitlab.com/neosimsim/hello-lenses#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  hello-lenses:
    main:                hello-lenses.lhs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - lens
  hello-lens:
    main:                hello-lens.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens
